### PR TITLE
Fix: SVG Attributes

### LINKED ISSUE #50: Attributes on SVG are ignored
**Describe the bug**

Whenever I try to pass role, id, or class no error shows in the IDE and the output HTML doesn't contain any of the inputted attributes.

I thought it might be SVGO, so I disabled it entirely, and the same issue exists.

Not sure if I am doing something wrong or if this is something that needs to be addressed.

**To Reproduce**

1. Import any minified SVG as a solid component.
2. Pass any attribute to the SVG component.

**Expected behavior**
The attribute should appear in the compiled DOM tree

**Desktop (please complete the following information if applicable):**
 - OS: Any
 - Browser: Any

**Smartphone (please complete the following information if applicable):**
 - Device: Any
 - OS: Any
 - Browser Any

**Additional context**
I opened an issue on the [vite-plugin-solid-svg](https://github.com/jfgodoy/vite-plugin-solid-svg) repo, and you can find it here: https://github.com/jfgodoy/vite-plugin-solid-svg/issues/43

And as per this [comment](https://github.com/jfgodoy/vite-plugin-solid-svg/issues/43#issuecomment-1870552569), we should update the `vite-plugin-solid-svg`  dependency

### PR DESCRIPTION
**Pull request by karimshalapy**
# Description

This PR does the following.
- Updates the `vite-plugin-solid-svg` dependency to solve the issue where minified SVGs ignored all the attributes passed to them. As per this comment: https://github.com/jfgodoy/vite-plugin-solid-svg/issues/43#issuecomment-1870552569
- Adds `role="presentation"` to all `?component-solid` imported SVGs.
- Fixes the `Badge`'s `statusIconMapping` type.

## Which issue does this PR resolve?

Resolves #50

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist (check all that don't apply as well):

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (if needed)
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/Badge/Badge.tsx [hunk 1]
```diff
@@ -10,11 +10,11 @@ import ForbiddenIcon from "~assets/icons/forbidden.svg?component-solid";
 import OliveIcon from "~assets/icons/olive.svg?component-solid";
 import IncognitoIcon from "~assets/icons/incognito.svg?component-solid";
 
-const statusIconMapping: Record<Status, Component> = {
+const statusIconMapping = {
 	alternative: OliveIcon,
 	boycott: ForbiddenIcon,
 	unsure: IncognitoIcon,
-};
+} satisfies Record<Status, Component>;
```
Comment (KL13NT) [inline src/components/Badge/Badge.tsx:17]: What's the problem here?

**Comment by KL13NT** [comment]
Let's also add the `alt=""` as per my comment on the issue #50

**Comment by karimshalapy** [comment]
@KL13NT You still think we need `alt=""` after this comment: https://github.com/KL13NT/badeel/issues/50#issuecomment-1870922167 ?

File: src/components/Badge/Badge.tsx (hunk 1 above)
Comment (karimshalapy) [reply src/components/Badge/Badge.tsx:17]: Saying `: Record<Status, Component>` means that each of the values in this `Record` will be of type `Component`, which is not true. Yes, they are `Component`s but they also have props that can be passed to them and just saying `Component` infers that they are `Component`s without any props in their type.  
 
The solution here is that we use [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html), and by saying `satisfies Record<Status, Component>`, we tell Typescript to make sure that it does follow the schema of `Component` but at the same time infer its type.

So if they don't follow the `Component` interface, an error will be thrown, but if they do you will see that their type is inferred as if the `satisfies` was never there.

Comment (karimshalapy) [reply src/components/Badge/Badge.tsx:17]: TLDR; When I was passing a `role` prop to the `Dynamic` component, it gave an error because the `Component` type didn't describe the props, so I had to infer the type of the icons, and `satisfies` does the job.

**Comment by KL13NT** [comment]
> @KL13NT You still think we need `alt=""` after this comment: [#50 (comment)](https://github.com/KL13NT/badeel/issues/50#issuecomment-1870922167) ?

Check https://github.com/KL13NT/badeel/issues/50#issuecomment-1871246065

**Review by KL13NT — APPROVED** [review]
